### ISSUE TITLE
benchmark performance (Broadcast News)

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/dane-whisper-asr-worker#37]
benchmark with the same setup for fair comparison:

- [ ] faster-whisper
- [ ] Whisper-X
- [ ] Huggingface transformers-implementation
- [ ] original OpenAI (baseline)

**Comment by greenw0lf** [comment]
Parameters to experiment with that apply to all implementations:
- float16 vs. float32 (whether there's a huge WER difference between the two, if not it is preferred to use float16 as it is faster and consumes less GPU memory)
- large-v2 vs. large-v3

**Comment by greenw0lf** [comment]
Labelled data benchmarked, unlabelled data still to go

**Comment by greenw0lf** [comment]
**Re-benchmarking faster-whisper** (both labelled and unlabelled) because time to transcribe should be measured from the point when `model.transcribe` is run until the output of the function is saved to a JSON file.

Also **re-benchmarking WhisperX** for the reason mentioned in the previous comment (expected less time spent per file)
